"""Tests for AWS Lambda configuration files generated by dsd-aws-lambda."""

import sys
from pathlib import Path

import pytest

from tests.integration_tests.utils import it_helper_functions as hf


# --- Tests for generated files ---


def test_settings(tmp_project):
    """Verify there's an AWS Lambda-specific settings section."""
    hf.check_reference_file(tmp_project, "blog/settings.py", "dsd-aws-lambda")


def test_requirements_txt(tmp_project, pkg_manager, tmp_path, dsd_version):
    """Verify requirements are correct for requirements.txt."""
    if pkg_manager == "req_txt":
        context = {"current-version": dsd_version}
        hf.check_reference_file(
            tmp_project,
            "requirements.txt",
            "dsd-aws-lambda",
            context=context,
        )
    elif pkg_manager in ("poetry", "pipenv"):
        # requirements.txt should not exist for poetry/pipenv.
        assert not Path(tmp_project / "requirements.txt").exists()


def test_pyproject_toml(tmp_project, pkg_manager, dsd_version):
    """Verify requirements added to pyproject.toml for Poetry."""
    if pkg_manager == "poetry":
        context = {"current-version": dsd_version}
        hf.check_reference_file(
            tmp_project,
            "pyproject.toml",
            "dsd-aws-lambda",
            context=context,
        )
    elif pkg_manager == "req_txt":
        pytest.skip("Not relevant for requirements.txt projects.")


def test_pipfile(tmp_project, pkg_manager, dsd_version):
    """Verify requirements added to Pipfile for Pipenv."""
    if pkg_manager == "pipenv":
        context = {"current-version": dsd_version}
        hf.check_reference_file(
            tmp_project,
            "Pipfile",
            "dsd-aws-lambda",
            context=context,
        )
    elif pkg_manager == "req_txt":
        pytest.skip("Not relevant for requirements.txt projects.")


def test_creates_lambda_handler(tmp_project):
    """Verify that lambda_handler.py is created."""
    path = tmp_project / "lambda_handler.py"
    assert path.exists()

    contents = path.read_text()
    assert "from mangum import Mangum" in contents
    assert "def handler(event, context):" in contents
    assert "manage" in contents


def test_creates_sam_template(tmp_project):
    """Verify that template.yaml (SAM template) is created."""
    path = tmp_project / "template.yaml"
    assert path.exists()

    contents = path.read_text()
    assert "AWS::Serverless-2016-10-31" in contents
    assert "DjangoFunction" in contents
    assert "HttpApi" in contents
    assert "StaticFilesBucket" in contents


def test_creates_samconfig(tmp_project):
    """Verify that samconfig.toml is created."""
    path = tmp_project / "samconfig.toml"
    assert path.exists()

    contents = path.read_text()
    assert "stack_name" in contents
    assert "CAPABILITY_IAM" in contents


def test_creates_static_dir(tmp_project):
    """Verify that the static/ directory is created."""
    static_dir = tmp_project / "static"
    assert static_dir.exists()
    assert (static_dir / ".gitkeep").exists()


def test_log_dir(tmp_project):
    """Test that the log directory exists, and contains an appropriate log file."""
    log_path = Path(tmp_project / "dsd_logs")
    assert log_path.exists()

    log_files = sorted(log_path.glob("*"))
    assert len(log_files) == 1

    log_file = log_files[0]
    log_file_text = log_file.read_text()

    assert "INFO: Logging run of `manage.py deploy`..." in log_file_text
    assert (
        "INFO: Configuring project for deployment to AWS Lambda..."
        in log_file_text
    )
