"""AWS Lambda-specific Django settings overrides.

Generated by the dsd-aws-sam plugin for projects whose settings.py does not
match the stock `django-admin startproject` layout (e.g. cookiecutter-django
with split settings, or projects that already read from env vars).

The plugin appends a single `from .aws_sam_settings import *` line to the
active Django settings module (resolved from DJANGO_SETTINGS_MODULE). Each
override below only takes effect when the corresponding env var is populated
-- in practice this means the SAM-deployed Lambda gets the Lambda-specific
values, while local dev (where the env vars are unset) keeps whatever the
importing module already defined.
"""

import os

_secret_key = os.environ.get("DJANGO_SECRET_KEY")
if _secret_key:
    SECRET_KEY = _secret_key

_debug = os.environ.get("DEBUG")
if _debug is not None:
    DEBUG = _debug.lower() in ("true", "1")

_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "")
if _allowed_hosts:
    ALLOWED_HOSTS = _allowed_hosts.split(",")

_csrf_trusted_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins.split(",")

_static_files_bucket = os.environ.get("STATIC_FILES_BUCKET", "")
if _static_files_bucket:
    AWS_STORAGE_BUCKET_NAME = _static_files_bucket
    AWS_S3_REGION_NAME = os.environ.get("AWS_REGION", "us-east-1")
    AWS_DEFAULT_ACL = None
    STORAGES = {
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        },
    }
    STATIC_URL = f"https://{_static_files_bucket}.s3.amazonaws.com/static/"

# CloudWatch-compatible logging. Applied unconditionally because the format is
# also reasonable for local dev, and overriding LOGGING in the Lambda runtime
# is what surfaces Django logs in CloudWatch.
if os.environ.get("AWS_LAMBDA_FUNCTION_NAME"):
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "standard": {
                "format": "[%(levelname)s] %(name)s: %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "standard",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
    }
